[versions]
velocity = "3.4.0-SNAPSHOT"
waterdog = "2.0.4-SNAPSHOT"
bungeecord = "1.21-R0.4"
spigot = "1.21.5-R0.1-SNAPSHOT"
fabric = "0.16.14"
fabric-language-kotlin = "1.13.4+kotlin.2.2.0"
nukkit = "1.0-SNAPSHOT"

# bStats
bstats = "3.1.0"

gson = "2.13.2"

yaml = "2.5"

[libraries]
# platforms
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
waterdog = { group = "dev.waterdog.waterdogpe", name = "waterdog", version.ref = "waterdog"}
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
nukkit = { group = "cn.nukkit", name = "nukkit", version.ref = "nukkit" }

fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

# bStats
bstats-spigot = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
bstats-velocity = { group = "org.bstats", name = "bstats-velocity", version.ref = "bstats" }
bstats-bungeecord = { group = "org.bstats", name = "bstats-bungeecord", version.ref = "bstats" }

snake-yaml = { group = "org.yaml", name = "snakeyaml", version.ref = "yaml" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[bundles]
fabric = ["fabric", "fabric-language-kotlin"]